### ISSUE TITLE
Getting the answers & path out?

### ISSUE THREAD

**Issue by MisterTea** [ghackebeil/pybnb#1]
Hey, cool library!

Maybe I'm missing something here, but it doesn't seem like there's any way to get the answers or the path to the answers out?  SolverResults doesn't have the best node and there's no bookeeping to keep the chain of nodes?

**Comment by ghackebeil** [comment]
Thanks!

My thinking was that I would leave it up to the user to implement how they want to handle storing the solution. For instance, one could save the problem state by implementing something in the optional method `Problem.notify_new_best_objective`, which is called by the solver when the most recent call to `Problem.objective` returns a new best objective.

But I do like your idea of at least saving one of the best nodes (there may be many) and either tacking it onto the results object or loading it into the Problem just before the solve finishes. I'm trying to put out another release in the next day or so. If I can't work that change in, I'll at least update the docs with a section about saving the best node.

Unfortunately, maintaining a chain of nodes from the root to the best isn't possible right now as I'm currently throwing away the parent node after branching. Is there any value in keeping the parent nodes around?

**Comment by MisterTea** [comment]
@ghackebeil The only reason to keep the chain of nodes is so people can retrace the steps to the solution (e.g. if using B&B to solve TSP or some other graph problem).

If there is a way to save the state using that optional method, how would that work in the context of MPI and multiple processes?  Someone would have to save it to a database or something?

At any rate, saving the solution should be in the example in some way/shape/form :-).

**Comment by ghackebeil** [comment]
@MisterTea: I've added a TSP example and short section to the online docs discussing this. It's all included in the latest release (0.3.0). Thanks for your feedback. I'll look into further integrating this into the solver in the next release.

**Comment by MisterTea** [comment]
Thanks!!
