### ISSUE TITLE
Access solver attributes within problem

### ISSUE THREAD

**Issue by TheoGuyard** [ghackebeil/pybnb#17]
Hi ! Thank you for the development of this package ! I was wondering if there was a way to call the solver attributes inside the problem methods. For instance, I would like to have access to the best objective within the bound method in the following way :

```python
class Problem(pybnb.Problem):
    ...
    def bound(self):
        best_objective = self.retrieve_solver_attribute("best_objective")
        return do_bounding_using_best_objective()
    ...
```

Thank you for your answer,
Théo

**Comment by ghackebeil** [comment]
Hi @TheoGuyard. Thanks for your interest in the project!

You can access the best node (i.e., the node with the best objective) each time it is updated by implementing a `notify_new_best_node` method on your Problem class.

https://pybnb.readthedocs.io/en/stable/reference/problem.html#pybnb.problem.Problem.notify_new_best_node

The best objective is available as the `objective` attribute on the node passed into that method, along with other information.

https://pybnb.readthedocs.io/en/stable/reference/node.html#pybnb.node.Node

This page shows where that method is called relative to others in the core solver loop:

https://pybnb.readthedocs.io/en/stable/getting_started/index.html#how-the-solver-calls-the-problem-methods

**Comment by TheoGuyard** [comment]
Hi @ghackebeil. Thanks for the quick response, I now have all the information I need !
