### ISSUE TITLE
Knapsack example

### ISSUE THREAD

**Issue by fudgepack** [ghackebeil/pybnb#6]
Can you include a knapsack implementation in your examples? I'm struggling a bit with the documentation. It would be helpful for newcomers to familiarize with your library.

**Comment by ghackebeil** [comment]
@fudgepack, there is a knapsack example [here](https://github.com/ghackebeil/pybnb/blob/master/examples/command_line_problems/binary_knapsack.py). Note that it is only compatible with the 0.4 release (put out a few minutes ago), so you  likely need to update.
